# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_1/first_zynq_system_rst_ps7_0_100M_1.xci
# IP: The module: 'first_zynq_system_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_1/first_zynq_system_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_1/first_zynq_system_rst_ps7_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_1/first_zynq_system_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_1/first_zynq_system_rst_ps7_0_100M_1.xci
# IP: The module: 'first_zynq_system_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_1/first_zynq_system_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_1/first_zynq_system_rst_ps7_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_rst_ps7_0_100M_1/first_zynq_system_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
